// luuVucSong.js
//
// Bảng tra "lưu vực sông" + thứ tự sắp xếp Bắc->Nam — khớp theo TÊN TRẠM đã
// chuẩn hoá (bỏ dấu, viết thường, gộp khoảng trắng) thay vì theo "id" — vì id
// của trạm mưa VRain được tạo linh động từ tên thật lấy trực tiếp từ API,
// có thể lệch nhẹ so với danh sách tĩnh, trong khi TÊN thường ổn định hơn.
// Theo đúng file anh Hudson đã rà soát/sắp xếp lại lần 2.
export const LUU_VUC_SONG = {
  'song thai': { thuTu: 0, luuVuc: 'Sông Ròn' },
  'quang hop': { thuTu: 1, luuVuc: 'Sông Ròn' },
  'roon': { thuTu: 3, luuVuc: 'Sông Ròn' },
  'vuc tron': { thuTu: 5, luuVuc: 'Sông Ròn' },
  'quang tung': { thuTu: 6, luuVuc: 'Sông Ròn' },
  'ho but': { thuTu: 7, luuVuc: 'Sông Ròn' },
  'huong hoa': { thuTu: 8, luuVuc: 'Sông Gianh' },
  'ho ho': { thuTu: 9, luuVuc: 'Sông Gianh' },
  'thanh hoa': { thuTu: 12, luuVuc: 'Sông Gianh' },
  'thuong hoa': { thuTu: 13, luuVuc: 'Sông Gianh' },
  'lam hoa': { thuTu: 15, luuVuc: 'Sông Gianh' },
  'hoa thanh': { thuTu: 16, luuVuc: 'Sông Gianh' },
  'trong hoa': { thuTu: 17, luuVuc: 'Sông Gianh' },
  'hoa son': { thuTu: 19, luuVuc: 'Sông Gianh' },
  'trung hoa': { thuTu: 20, luuVuc: 'Sông Gianh' },
  'dan hoa 2': { thuTu: 21, luuVuc: 'Sông Gianh' },
  'tan hoa': { thuTu: 22, luuVuc: 'Sông Gianh' },
  'minh hoa': { thuTu: 23, luuVuc: 'Sông Gianh' },
  'tuyen hoa': { thuTu: 25, luuVuc: 'Sông Gianh' },
  'đong tam': { thuTu: 26, luuVuc: 'Sông Gianh' },
  'tan lam': { thuTu: 28, luuVuc: 'Sông Gianh' },
  'mai hoa': { thuTu: 30, luuVuc: 'Sông Gianh' },
  'quang tien': { thuTu: 32, luuVuc: 'Sông Gianh' },
  'trung thuan': { thuTu: 33, luuVuc: 'Sông Gianh' },
  'quang trach': { thuTu: 34, luuVuc: 'Sông Gianh' },
  'quang thanh': { thuTu: 35, luuVuc: 'Sông Gianh' },
  'ba đon': { thuTu: 36, luuVuc: 'Sông Gianh' },
  'tan my': { thuTu: 37, luuVuc: 'Sông Gianh' },
  'ho đong ran': { thuTu: 39, luuVuc: 'Sông Gianh' },
  'bac trach': { thuTu: 40, luuVuc: 'Sông Gianh' },
  'cao quang': { thuTu: 41, luuVuc: 'Rào nan - Gianh' },
  'rao nan': { thuTu: 42, luuVuc: 'Rào nan - Gianh' },
  'xuan trach': { thuTu: 43, luuVuc: 'Son - Gianh' },
  'phuc trach': { thuTu: 44, luuVuc: 'Son - Gianh' },
  'phong nha': { thuTu: 46, luuVuc: 'Son - Gianh' },
  'son trach': { thuTu: 48, luuVuc: 'Son - Gianh' },
  'lien trach': { thuTu: 49, luuVuc: 'Son - Gianh' },
  'quang minh': { thuTu: 51, luuVuc: 'Son - Gianh' },
  'van trach': { thuTu: 52, luuVuc: 'Sông Lý Hòa' },
  'ly hoa': { thuTu: 53, luuVuc: 'Sông Lý Hòa' },
  'thac chuoi': { thuTu: 55, luuVuc: 'Sông Dinh' },
  'viet trung': { thuTu: 56, luuVuc: 'Sông Dinh' },
  'truong son 2': { thuTu: 58, luuVuc: 'Long Đại - Nhật Lệ' },
  'truong son': { thuTu: 59, luuVuc: 'Long Đại - Nhật Lệ' },
  'đong hoi': { thuTu: 61, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'quan hau': { thuTu: 64, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'troc trau': { thuTu: 65, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'ham ninh': { thuTu: 66, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'truong xuan': { thuTu: 67, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'van ninh': { thuTu: 68, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'le thuy': { thuTu: 69, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'ttnt. le ninh': { thuTu: 71, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'an ma': { thuTu: 72, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'lam thuy': { thuTu: 73, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'kim ngan': { thuTu: 74, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'kien giang': { thuTu: 75, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'cam ly': { thuTu: 79, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'con co': { thuTu: 81, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'thai thuy': { thuTu: 82, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'truong thuy': { thuTu: 83, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'sen thuy': { thuTu: 84, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'đo mua tđ sen thuy': { thuTu: 85, luuVuc: 'Kiến Giang - Nhật Lệ' },
  'vinh tu': { thuTu: 86, luuVuc: 'Bến Hải' },
  'vinh kim': { thuTu: 87, luuVuc: 'Bến Hải' },
  'vinh khe': { thuTu: 89, luuVuc: 'Bến Hải' },
  'bao đai': { thuTu: 90, luuVuc: 'Bến Hải' },
  'cua tung': { thuTu: 91, luuVuc: 'Bến Hải' },
  'la nga': { thuTu: 92, luuVuc: 'Bến Hải' },
  'ben quan': { thuTu: 93, luuVuc: 'Bến Hải' },
  'hien luong': { thuTu: 95, luuVuc: 'Bến Hải' },
  'trung son': { thuTu: 97, luuVuc: 'Bến Hải' },
  'gia vong': { thuTu: 98, luuVuc: 'Bến Hải' },
  'vinh o': { thuTu: 100, luuVuc: 'Bến Hải' },
  'linh thuong': { thuTu: 102, luuVuc: 'Bến Hải' },
  'cua viet': { thuTu: 103, luuVuc: 'Thach Hãn - Hiếu' },
  'huong lap': { thuTu: 105, luuVuc: 'Thach Hãn - Hiếu' },
  'ho truc kinh': { thuTu: 106, luuVuc: 'Thach Hãn - Hiếu' },
  'hai thai': { thuTu: 107, luuVuc: 'Thach Hãn - Hiếu' },
  'truc kinh': { thuTu: 108, luuVuc: 'Thach Hãn - Hiếu' },
  'đong ha': { thuTu: 109, luuVuc: 'Thach Hãn - Hiếu' },
  'trieu đo': { thuTu: 110, luuVuc: 'Thach Hãn - Hiếu' },
  'trieu đai': { thuTu: 111, luuVuc: 'Thach Hãn - Hiếu' },
  'huong viet': { thuTu: 112, luuVuc: 'Thach Hãn - Hiếu' },
  'đa mai': { thuTu: 115, luuVuc: 'Thach Hãn - Hiếu' },
  'cam tuyen': { thuTu: 116, luuVuc: 'Thach Hãn - Hiếu' },
  'trieu hoa': { thuTu: 118, luuVuc: 'Thach Hãn - Hiếu' },
  'cam thanh': { thuTu: 119, luuVuc: 'Thach Hãn - Hiếu' },
  'đau mau': { thuTu: 120, luuVuc: 'Thach Hãn - Hiếu' },
  'vinh phuoc': { thuTu: 122, luuVuc: 'Thach Hãn - Hiếu' },
  'hai an': { thuTu: 123, luuVuc: 'Thach Hãn - Hiếu' },
  'ho ai tu': { thuTu: 124, luuVuc: 'Thach Hãn - Hiếu' },
  'huong son': { thuTu: 125, luuVuc: 'Thach Hãn - Hiếu' },
  'huong hiep': { thuTu: 126, luuVuc: 'Thach Hãn - Hiếu' },
  'trieu ai': { thuTu: 128, luuVuc: 'Thach Hãn - Hiếu' },
  'cam chinh': { thuTu: 129, luuVuc: 'Thach Hãn - Hiếu' },
  'huong phung': { thuTu: 130, luuVuc: 'Thach Hãn - Hiếu' },
  'thach han': { thuTu: 133, luuVuc: 'Thach Hãn - Hiếu' },
  'huong linh': { thuTu: 135, luuVuc: 'Thach Hãn - Hiếu' },
  'ho nam thach han': { thuTu: 136, luuVuc: 'Thach Hãn - Hiếu' },
  'nam thach han': { thuTu: 137, luuVuc: 'Thach Hãn - Hiếu' },
  'cay da': { thuTu: 138, luuVuc: 'Thach Hãn - Hiếu' },
  'hai lam': { thuTu: 139, luuVuc: 'Thach Hãn - Hiếu' },
  'tđ quang tri': { thuTu: 141, luuVuc: 'Thach Hãn - Hiếu' },
  'thuy đien quang tri': { thuTu: 142, luuVuc: 'Thach Hãn - Hiếu' },
  'hai phong': { thuTu: 143, luuVuc: 'Thach Hãn - Hiếu' },
  'dakrong': { thuTu: 144, luuVuc: 'Thach Hãn - Hiếu' },
  'hai tan': { thuTu: 146, luuVuc: 'Thach Hãn - Hiếu' },
  'đakrong 2': { thuTu: 147, luuVuc: 'Thach Hãn - Hiếu' },
  'ba long': { thuTu: 148, luuVuc: 'Thach Hãn - Hiếu' },
  'my chanh': { thuTu: 150, luuVuc: 'Thach Hãn - Hiếu' },
  'tan long': { thuTu: 152, luuVuc: 'Thach Hãn - Hiếu' },
  'ba nang': { thuTu: 153, luuVuc: 'Thach Hãn - Hiếu' },
  'ta long': { thuTu: 154, luuVuc: 'Thach Hãn - Hiếu' },
  'la to': { thuTu: 155, luuVuc: 'Thach Hãn - Hiếu' },
  'ta rut': { thuTu: 156, luuVuc: 'Thach Hãn - Hiếu' },
  'a vao': { thuTu: 159, luuVuc: 'Thach Hãn - Hiếu' },
  'a bung': { thuTu: 160, luuVuc: 'Thach Hãn - Hiếu' },
  'khe sanh': { thuTu: 161, luuVuc: 'Sê Pôn' },
  'lao bao': { thuTu: 163, luuVuc: 'Sê Pôn' },
  'huc': { thuTu: 164, luuVuc: 'Sê Pôn' },
  'huong loc': { thuTu: 165, luuVuc: 'Sê Pôn' },
  'thanh': { thuTu: 166, luuVuc: 'Sê Pôn' },
  'a doi': { thuTu: 167, luuVuc: 'Sê Pôn' },
  'lia': { thuTu: 168, luuVuc: 'Sê Pôn' },
};

// Chuẩn hoá tên trạm: bỏ dấu tiếng Việt, viết thường, gộp khoảng trắng —
// khớp đúng cách xử lý bên Python lúc tạo bảng tra này.
function chuanHoaTen(ten) {
  return String(ten).normalize('NFKD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase().trim().replace(/\s+/g, ' ');
}

// Lấy thông tin lưu vực + thứ tự cho 1 trạm theo TÊN — nếu không tìm thấy
// (trạm mới chưa kịp cập nhật), trả về thứ tự lớn (xếp cuối) + lưu vực rỗng.
export function layLuuVuc(ten) {
  return LUU_VUC_SONG[chuanHoaTen(ten)] || { thuTu: 9999, luuVuc: '' };
}