// luuVucSong.js
//
// Bảng tra "lưu vực sông" + thứ tự sắp xếp Bắc->Nam — khớp theo TÊN TRẠM đã
// chuẩn hoá (bỏ dấu, viết thường, gộp khoảng trắng). Theo file anh Hudson gửi
// (Vitri_tramdotudong.xlsx), gồm cả "Dakrong 2".
export const LUU_VUC_SONG = {
  'quang hop': { thuTu: 0, luuVuc: 'Ròn' },
  'roon': { thuTu: 1, luuVuc: 'Ròn' },
  'quang tung': { thuTu: 2, luuVuc: 'Ròn' },
  'ho vuc tron': { thuTu: 3, luuVuc: 'Ròn' },
  'ho song thai': { thuTu: 4, luuVuc: 'Ròn' },
  'thuy van roon': { thuTu: 5, luuVuc: 'Ròn' },
  'huong hoa': { thuTu: 6, luuVuc: 'Gianh' },
  'thanh hoa': { thuTu: 7, luuVuc: 'Gianh' },
  'lam hoa': { thuTu: 8, luuVuc: 'Gianh' },
  'đong tam': { thuTu: 9, luuVuc: 'Gianh' },
  'tan lam': { thuTu: 11, luuVuc: 'Gianh' },
  'hoa thanh': { thuTu: 13, luuVuc: 'Gianh' },
  'tuyen hoa': { thuTu: 14, luuVuc: 'Gianh' },
  'trong hoa': { thuTu: 15, luuVuc: 'Gianh' },
  'đong lam, đuc hoa': { thuTu: 16, luuVuc: 'Gianh' },
  'quang tien': { thuTu: 17, luuVuc: 'Gianh' },
  'ho be': { thuTu: 18, luuVuc: 'Gianh' },
  'mai hoa': { thuTu: 19, luuVuc: 'Gianh' },
  'đau moi ho trung thuan': { thuTu: 21, luuVuc: 'Gianh' },
  'minh hoa': { thuTu: 22, luuVuc: 'Gianh' },
  'quang trach': { thuTu: 23, luuVuc: 'Gianh' },
  'tan hoa': { thuTu: 24, luuVuc: 'Gianh' },
  'tdc 8, thi tran quy đat': { thuTu: 25, luuVuc: 'Gianh' },
  'cao quang': { thuTu: 26, luuVuc: 'Gianh' },
  'thuy van rao nan, cao quang': { thuTu: 27, luuVuc: 'Gianh' },
  'rao nan': { thuTu: 28, luuVuc: 'Gianh' },
  'tu lan lodge': { thuTu: 29, luuVuc: 'Gianh' },
  'hoa son': { thuTu: 30, luuVuc: 'Gianh' },
  'quang thanh': { thuTu: 32, luuVuc: 'Gianh' },
  'ba đon': { thuTu: 33, luuVuc: 'Gianh' },
  'trung hoa': { thuTu: 34, luuVuc: 'Gianh' },
  'quang minh': { thuTu: 35, luuVuc: 'Gianh' },
  'thuong hoa': { thuTu: 36, luuVuc: 'Gianh' },
  'tan my': { thuTu: 37, luuVuc: 'Gianh' },
  'ho đong ran': { thuTu: 39, luuVuc: 'Gianh' },
  'bac trach': { thuTu: 40, luuVuc: 'Gianh' },
  'lien trach': { thuTu: 41, luuVuc: 'Gianh' },
  'thuy van lien trach': { thuTu: 42, luuVuc: 'Gianh' },
  'xuan trach': { thuTu: 44, luuVuc: 'Gianh' },
  'phuc trach': { thuTu: 45, luuVuc: 'Gianh' },
  'phong nha': { thuTu: 46, luuVuc: 'Gianh' },
  'ly hoa': { thuTu: 48, luuVuc: 'Lý hòa' },
  'thuy van ly hoa': { thuTu: 49, luuVuc: 'Lý hòa' },
  'van trach': { thuTu: 50, luuVuc: 'Lý hòa' },
  'ho thac chuoi': { thuTu: 51, luuVuc: 'Dinh' },
  'viet trung': { thuTu: 52, luuVuc: 'Dinh' },
  'đong hoi': { thuTu: 53, luuVuc: 'Kiến Giang' },
  'quan hau': { thuTu: 56, luuVuc: 'Kiến Giang' },
  'ho trooc trau': { thuTu: 57, luuVuc: 'Kiến Giang' },
  'ham ninh': { thuTu: 58, luuVuc: 'Kiến Giang' },
  'van ninh': { thuTu: 59, luuVuc: 'Kiến Giang' },
  'truong xuan pctt': { thuTu: 60, luuVuc: 'Kiến Giang' },
  'le thuy': { thuTu: 61, luuVuc: 'Kiến Giang' },
  'truong son': { thuTu: 62, luuVuc: 'Kiến Giang' },
  'cam ly': { thuTu: 67, luuVuc: 'Kiến Giang' },
  'ho cam ly': { thuTu: 68, luuVuc: 'Kiến Giang' },
  'truong son 2': { thuTu: 69, luuVuc: 'Kiến Giang' },
  'thai thuy': { thuTu: 70, luuVuc: 'Kiến Giang' },
  'đo mua tđ sen thuy': { thuTu: 71, luuVuc: 'Kiến Giang' },
  'kien giang': { thuTu: 72, luuVuc: 'Kiến Giang' },
  'vinh tu': { thuTu: 74, luuVuc: 'Kiến Giang' },
  'ho an ma': { thuTu: 75, luuVuc: 'Kiến Giang' },
  'kim ngan': { thuTu: 76, luuVuc: 'Kiến Giang' },
  'vinh kim': { thuTu: 77, luuVuc: 'Kiến Giang' },
  'vinh khe': { thuTu: 78, luuVuc: 'Kiến Giang' },
  'lam thuy': { thuTu: 79, luuVuc: 'Kiến Giang' },
  'con co': { thuTu: 80, luuVuc: 'Bến Hải' },
  'đau moi ho bao đai': { thuTu: 81, luuVuc: 'Bến Hải' },
  'cua tung': { thuTu: 82, luuVuc: 'Bến Hải' },
  'đau moi ho la nga': { thuTu: 83, luuVuc: 'Bến Hải' },
  'ben quan': { thuTu: 84, luuVuc: 'Bến Hải' },
  'hien luong': { thuTu: 86, luuVuc: 'Bến Hải' },
  'trung son': { thuTu: 88, luuVuc: 'Bến Hải' },
  'gia vong': { thuTu: 89, luuVuc: 'Bến Hải' },
  'vinh o': { thuTu: 91, luuVuc: 'Bến Hải' },
  'linh thuong': { thuTu: 92, luuVuc: 'Bến Hải' },
  'cua viet': { thuTu: 93, luuVuc: 'Thạch Hãn' },
  'huong lap': { thuTu: 95, luuVuc: 'Thạch Hãn' },
  'ho truc kinh': { thuTu: 96, luuVuc: 'Thạch Hãn' },
  'hai thai': { thuTu: 97, luuVuc: 'Thạch Hãn' },
  'đau moi ho truc kinh': { thuTu: 98, luuVuc: 'Thạch Hãn' },
  'đong ha': { thuTu: 99, luuVuc: 'Thạch Hãn' },
  'trieu đo': { thuTu: 100, luuVuc: 'Thạch Hãn' },
  'trieu đai': { thuTu: 101, luuVuc: 'Thạch Hãn' },
  'huong viet': { thuTu: 102, luuVuc: 'Thạch Hãn' },
  'đau moi ho đa mai': { thuTu: 105, luuVuc: 'Thạch Hãn' },
  'cam tuyen': { thuTu: 106, luuVuc: 'Thạch Hãn' },
  'trieu hoa': { thuTu: 108, luuVuc: 'Thạch Hãn' },
  'tt phong tranh va giam nhe thien tai': { thuTu: 109, luuVuc: 'Thạch Hãn' },
  'đau mau': { thuTu: 110, luuVuc: 'Thạch Hãn' },
  'vinh phuoc': { thuTu: 112, luuVuc: 'Thạch Hãn' },
  'hai an': { thuTu: 113, luuVuc: 'Thạch Hãn' },
  'ho ai tu': { thuTu: 114, luuVuc: 'Thạch Hãn' },
  'huong son': { thuTu: 115, luuVuc: 'Thạch Hãn' },
  'huong hiep': { thuTu: 116, luuVuc: 'Thạch Hãn' },
  'trieu ai': { thuTu: 117, luuVuc: 'Thạch Hãn' },
  'cam chinh': { thuTu: 118, luuVuc: 'Thạch Hãn' },
  'huong phung pctt': { thuTu: 119, luuVuc: 'Thạch Hãn' },
  'thach han': { thuTu: 121, luuVuc: 'Thạch Hãn' },
  'huong linh': { thuTu: 123, luuVuc: 'Thạch Hãn' },
  'ho nam thach han': { thuTu: 124, luuVuc: 'Thạch Hãn' },
  'nam thach han': { thuTu: 125, luuVuc: 'Thạch Hãn' },
  'cay da': { thuTu: 126, luuVuc: 'Thạch Hãn' },
  'hai lam': { thuTu: 127, luuVuc: 'Thạch Hãn' },
  'tđ quang tri': { thuTu: 129, luuVuc: 'Thạch Hãn' },
  'hai phong': { thuTu: 130, luuVuc: 'Thạch Hãn' },
  'dakrong': { thuTu: 131, luuVuc: 'Thạch Hãn' },
  'dakrong 2': { thuTu: 133, luuVuc: 'Thạch Hãn' },
  'hai tan': { thuTu: 134, luuVuc: 'Thạch Hãn' },
  'ba long': { thuTu: 135, luuVuc: 'Thạch Hãn' },
  'my chanh': { thuTu: 136, luuVuc: 'Thạch Hãn' },
  'tan long': { thuTu: 138, luuVuc: 'Thạch Hãn' },
  'ba nang': { thuTu: 139, luuVuc: 'Thạch Hãn' },
  'ta long': { thuTu: 140, luuVuc: 'Thạch Hãn' },
  'đap, thuy đien la to': { thuTu: 141, luuVuc: 'Thạch Hãn' },
  'ta rut': { thuTu: 142, luuVuc: 'Thạch Hãn' },
  'a vao': { thuTu: 144, luuVuc: 'Thạch Hãn' },
  'a bung': { thuTu: 145, luuVuc: 'Thạch Hãn' },
  'khe sanh': { thuTu: 146, luuVuc: 'Sê Pôn' },
  'lao bao': { thuTu: 147, luuVuc: 'Sê Pôn' },
  'huc': { thuTu: 148, luuVuc: 'Sê Pôn' },
  'huong loc': { thuTu: 149, luuVuc: 'Sê Pôn' },
  'thanh': { thuTu: 150, luuVuc: 'Sê Pôn' },
  'a doi': { thuTu: 151, luuVuc: 'Sê Pôn' },
  'lia': { thuTu: 152, luuVuc: 'Sê Pôn' },
};

function chuanHoaTen(ten) {
  return String(ten).normalize('NFKD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase().trim().replace(/\s+/g, ' ');
}

export function layLuuVuc(ten) {
  return LUU_VUC_SONG[chuanHoaTen(ten)] || { thuTu: 9999, luuVuc: '' };
}